name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ * ]

jobs:
  build:

    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
