name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v4
    - name: install_devkitpro
      run: wget -U "dkp-apt" https://apt.devkitpro.org/install-devkitpro-pacman && chmod +x ./install-devkitpro-pacman && sudo ./install-devkitpro-pacman
    - name: make
      run: make
